//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movie()
        {
            this.MovieMapping = new HashSet<MovieMapping>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
        public System.DateTime YearOfRelease { get; set; }
        public System.DateTime Availability { get; set; }
        public string Description { get; set; }
        public bool IsFeatured { get; set; }
        public string PosterURL { get; set; }
        public string ContentURL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieMapping> MovieMapping { get; set; }
    }
}
